// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgBrNnDyvxKrV61m-Ul0xD8Sgo_YQ5es',
    appId: '1:898725893923:web:8ac831e2a8ca3f1af9de96',
    messagingSenderId: '898725893923',
    projectId: 'minimal-social-app-50e87',
    authDomain: 'minimal-social-app-50e87.firebaseapp.com',
    storageBucket: 'minimal-social-app-50e87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5LO8ZJxOdF8dXup23IJfNQGAJ01AmWs',
    appId: '1:898725893923:android:cbb48d3f66feffe7f9de96',
    messagingSenderId: '898725893923',
    projectId: 'minimal-social-app-50e87',
    storageBucket: 'minimal-social-app-50e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRckRKzxI1LIIhml1LIaOc0oTW66HcV0',
    appId: '1:898725893923:ios:e7e7bd10c97e8947f9de96',
    messagingSenderId: '898725893923',
    projectId: 'minimal-social-app-50e87',
    storageBucket: 'minimal-social-app-50e87.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRckRKzxI1LIIhml1LIaOc0oTW66HcV0',
    appId: '1:898725893923:ios:e7e7bd10c97e8947f9de96',
    messagingSenderId: '898725893923',
    projectId: 'minimal-social-app-50e87',
    storageBucket: 'minimal-social-app-50e87.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAgBrNnDyvxKrV61m-Ul0xD8Sgo_YQ5es',
    appId: '1:898725893923:web:f415a129a389e764f9de96',
    messagingSenderId: '898725893923',
    projectId: 'minimal-social-app-50e87',
    authDomain: 'minimal-social-app-50e87.firebaseapp.com',
    storageBucket: 'minimal-social-app-50e87.appspot.com',
  );
}
